from django.urls import path

from chat.http.views import (
    accept_pending,
    delete_image,
    delete_room,
    delete_user,
    dm_history,
    enter_room,
    index,
    list_friends,
    list_pending_requests,
    reject_pending,
    room,
    room_control_list,
    room_unread_state,
    serve_image,
    set_room_deleted_status,
    set_user_active_status,
    signup,
    signup_pending,
    unread_count,
    upload_image,
    user_approval_list,
)

urlpatterns = [
    path("", index, name="index"),
    path("rooms/enter/", enter_room, name="enter-room"),
    path("signup/", signup, name="signup"),
    path("signup/pending/", signup_pending, name="signup-pending"),
    path("chat/<str:public_id>/", room, name="room"),
    path("chat/<str:public_id>/image/", upload_image, name="upload-image"),
    path("chat/image/<int:image_id>/", serve_image, name="serve-image"),
    path("chat/image/<int:image_id>/delete/", delete_image, name="delete-image"),
    path("control/users/", user_approval_list, name="admin-user-approval-list"),
    path("control/users/<int:user_id>/active/", set_user_active_status, name="admin-user-set-active"),
    path("control/users/<int:user_id>/delete/", delete_user, name="admin-user-delete"),
    path("control/rooms/", room_control_list, name="admin-room-control-list"),
    path("control/rooms/<int:room_id>/deleted/", set_room_deleted_status, name="admin-room-set-deleted"),
    path("control/rooms/<int:room_id>/delete/", delete_room, name="admin-room-delete"),
    path("api/friends/", list_friends, name="api-friends-list"),
    path("api/friends/requests/", list_pending_requests, name="api-friends-requests"),
    path("api/friends/accept/", accept_pending, name="api-friends-accept"),
    path("api/friends/reject/", reject_pending, name="api-friends-reject"),
    path("api/friends/<str:peer_username>/messages/", dm_history, name="api-dm-history"),
    path("api/friends/unread-count/", unread_count, name="api-friends-unread-count"),
    path("api/rooms/<str:public_id>/unread/", room_unread_state, name="api-room-unread"),
]
