# Generated by Django 6.0.4 on 2026-04-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_edited_at_chatmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
