# Generated by Django 6.0.4 on 2026-04-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatimage_user_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='password_length',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
