# Generated by Django 6.0.4 on 2026-05-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatroom_password_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='public_id',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
    ]
