# Generated by Django 6.0.4 on 2026-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_chatroom_public_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='public_id',
            field=models.CharField(db_index=True, default='', editable=False, max_length=64, unique=True),
        ),
    ]
