# Generated by Django 6.0.4 on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0020_roomfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomfavorite",
            name="note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
