# Generated by Django 6.0.4 on 2026-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0021_backfill_user_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="custom_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="custom_icon",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
