# Generated by Django 6.0.4 on 2026-06-14 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0021_roomfavorite_note"),
        ("chat", "0022_chatroom_custom_color_chatroom_custom_icon"),
    ]

    operations = []
